## postfwd2 FreeBSD tasks
---
- name: install packages for FreeBSD
  tags:
    - postfwd2
    - packages
  pkgng: pkg={{item}} state=present
  with_items: postfwd2_package_names

- name: check postfwd2 for FreeBSD
  tags:
    - postfwd2
    - packages
  stat: path={{ postfwd2_bin }}
  register: check_postfwd2

- name: fetch postfwd2 for FreeBSD
  tags:
    - postfwd2
    - packages
  get_url: > 
    url=http://postfwd.org/postfwd2
    dest={{ postfwd2_bin }}
    force=yes
    sha256sum=bb0999def93e8289f148f0d192adafd0ce48b67fe2f36c3a475fcab6b35b4135
    owner={{ postfwd2_default_owner }}
    group={{ postfwd2_default_group }}
    mode=0755
  when: check_postfwd2.stat.exists == False

- name: fix binary path for FreeBSD
  tags:
    - postfwd2
    - packages
  lineinfile: dest={{ postfwd2_bin }} regexp='^#!/usr/bin/perl' line='#!/usr/local/bin/perl'

- name: create postfwd symlink for FreeBSD
  tags:
    - postfwd2
    - packages
  file: >
    src={{ postfwd2_bin }}
    dest={{ postfwd2_sym }}
    owner={{ postfwd2_default_owner }}
    group={{ postfwd2_default_group }}
    state=link

- name: install postfwd2 initd for FreeBSD
  tags:
    - postfwd2
    - packages
  template: >
    src=postfwd2-fbsd.initd
    dest=/usr/local/etc/rc.d/postfwd2
    owner={{ postfwd2_default_owner }}
    group={{ postfwd2_default_group }}
    mode=0755
  notify:
    - restart postfwd2
